name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        rust:
          - stable
          - nightly
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust Packages
        shell: cmd
        run: |
          rustup default %{{ matrix.rust }}
          rustup component add rustfmt clippy

      - name: Build
        run: |
          cargo build
          cargo build --release

      - name: Test
        run: |
          cargo test
          cargo test --release

      - name: Run Clippy
        run: cargo clippy -- -A warnings

      - name: Check Formatting
        run: cargo fmt -- --check
