name: CI

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        rust:
          - stable
          - nightly
        os:
          - windows-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust Packages
        run: |
          rustup default ${{ matrix.rust }}
          rustup component add rustfmt clippy

      - name: Enable problem matchers
        run: echo ::add-matcher::.github/problem_matchers.json
        if: ${{ matrix.rust == 'nightly' && matrix.os == 'ubuntu-latest' }}

      - name: Build (debug)
        run: cargo build

      - name: Build (release)
        run: cargo build --release

      - name: Test (debug)
        run: cargo test

      - name: Test (release)
        run: cargo test --release

      - name: Run Clippy
        run: cargo clippy --all-targets

      - name: Generate Docs
        run: cargo doc --no-deps --document-private-items

      - name: Check Formatting
        run: cargo fmt --check --all
